name: MacOS

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'docs/**'
    - '.gitattributes'
    - '.gitignore'
    - 'LICENSE.md'
    - 'README.md'

  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'docs/**'
    - '.gitattributes'
    - '.gitignore'
    - 'LICENSE.md'
    - 'README.md'

jobs:
  build:
    name: ${{ matrix.arch }}
    runs-on: macos-latest

    strategy:
      fail-fast: false  # if a particular matrix build fails, don't skip the rest
      matrix:
        arch: [x64]  # TODO: arm64 and universal2

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: brew install sdl2 sdl2_image sdl2_mixer sdl2_net sdl2_ttf

    - name: Build source and tests
      run: python3 build.py --make installer

    - name: Run tests
      run: python3 build.py --make test

    - name: Upload Binaries
      uses: actions/upload-artifact@v3.0.0
      with:
        name: kithare-darwin-${{ matrix.arch }}-installers
        path: dist/packaging/
