name: Windows

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'docs/**'
    - 'misc/**'
    - '.gitattributes'
    - '.gitignore'
    - 'LICENSE'
    - 'README.md'

  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'docs/**'
    - 'misc/**'
    - '.gitattributes'
    - '.gitignore'
    - 'LICENSE'
    - 'README.md'

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false  # if a particular matrix build fails, don't skip the rest
      matrix:
        arch: ['x64', 'x86']

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Build sources, tests and make installer
      run: python3 build.py --make installer --arch ${{ matrix.arch }}
    
    - name: Run tests
      run: python3 build.py --make test --arch ${{ matrix.arch }}
    
    # TODO: Test with installed kcr as well
    - name: Upload installer
      uses: actions/upload-artifact@v2
      with:
        name: kithare-windows-installers
        path: dist/packaging/
